### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by talamortis** [talamortis/mangos-tbc#1]
- [x] Implement **Azeorthcore / Trinitycore** Scripting Structure
- [x] Implement **Modular System** From Oregoncore / Azerothcore
- - [x] Make Modular Config DB Driven - Oregoncore Style.
- [x] Implement **PlayerScript** Hooks
- - [x] OnBeforePlayerUpdate
- - [x] OnLootItem
- - [x] OnPvPKill
- - [x] OnCreatureKill
- - [x] OnPlayerKilledByCreature
- - [x] OnCreateItem
- - [x] OnQuestRewardItem
- - [x] OnLevelChanged
- - [x] OnFreeTalentPointsChanged
- - [x] OnPlayerMoneyChanged
- - [x] OnMoneyLimit
- - [x] OnGiveXP
- - [x] OnPlayerReputationChange
- - [x] OnDuelStart
- - [x] OnDuelEnd
- - [x] OnChat
- - [x] OnSpellCast
- - [x] OnPlayerLogin
- - [x] OnPlayerLogout
- - [x] OnPlayerCreate
- - [x] OnPlayerLoadFromDB
- - [x] OnCharacterDelete
- - [x] OnFailedDelete
- - [x] OnPlayerSave
- - [x] OnBindToInstance
- - [x] OnUpdateZone
- [x] Implement **CreatureScript** Hooks
- [x] Implement **GameObjectScript** Hooks
- [ ] Implement **itemScript** Hooks
- [ ] Implement **AreaTrigger** Hooks
- [x] Implement **WorldScripts** Hooks

**Comment by yuanf225** [comment]
Did you transfer from Oregoncore to cmangos?

**Comment by diluh** [comment]
@talamortis Hello it seems interesting this system of modules similar to OregonCore, intends to update this repository? I can't wait to test it

**Comment by talamortis** [comment]
Im trying to merge both structures and implement the module system same as Oregon core, its a long window process and at the moment im finding it hard to get time to contribute
